2012-11-19 11:37:59,058 [   INFO] Forge tools running at version 3.3.28
2012-11-19 11:37:59,063 [  DEBUG] Forge build tools version: 3.3.28
2012-11-19 11:37:59,064 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-11-19 11:37:59,084 [  DEBUG] GET https://trigger.io/api/version_check/3/3/28/
2012-11-19 11:37:59,701 [  DEBUG] Checking API response for success or error
2012-11-19 11:37:59,701 [   INFO] Update result: you already have the latest tools
2012-11-19 11:37:59,704 [  DEBUG] GET https://trigger.io/api/auth/loggedin
2012-11-19 11:37:59,869 [  DEBUG] Checking API response for success or error
2012-11-19 11:37:59,869 [  DEBUG] already authenticated via cookie - continuing
2012-11-19 11:37:59,869 [  DEBUG] GET https://trigger.io/api/app/eb276e38325311e29d9a12313d31f141/should_rebuild
2012-11-19 11:38:00,041 [  DEBUG] Checking API response for success or error
2012-11-19 11:38:00,209 [  DEBUG] configuration is identical to last run
2012-11-19 11:38:00,210 [  DEBUG] already authenticated - continuing
2012-11-19 11:38:00,210 [  DEBUG] POST https://trigger.io/api/reload/buildevents/eb276e38325311e29d9a12313d31f141
2012-11-19 11:38:00,475 [  DEBUG] Checking API response for success or error
2012-11-19 11:38:00,475 [  ERROR] Target required for 'forge build', e.g. 'forge build android'
2012-11-19 11:38:00,475 [  DEBUG] Traceback (most recent call last):
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/async.py", line 96, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/main.py", line 358, in development_build
    raise ForgeError(FORGE_BUILD_NEEDS_TARGET)
ForgeError: Target required for 'forge build', e.g. 'forge build android'

2012-11-19 11:38:26,896 [   INFO] Forge tools running at version 3.3.28
2012-11-19 11:38:27,099 [  DEBUG] ignoring non-target directory reload
2012-11-19 11:38:27,099 [  DEBUG] Enabled platforms: ['ios']
2012-11-19 11:38:27,099 [  DEBUG] Forge build tools version: 3.3.28
2012-11-19 11:38:27,099 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-11-19 11:38:27,099 [  DEBUG] GET https://trigger.io/api/auth/loggedin
2012-11-19 11:38:27,765 [  DEBUG] Checking API response for success or error
2012-11-19 11:38:27,766 [  DEBUG] already authenticated via cookie - continuing
2012-11-19 11:38:27,766 [  DEBUG] POST https://trigger.io/api/track/
2012-11-19 11:38:27,930 [  DEBUG] Checking API response for success or error
2012-11-19 11:38:27,931 [  DEBUG] <ForgeTask (ios)> running...
2012-11-19 11:38:27,931 [  DEBUG] <ForgeTask (ios)> script:
[{'do': {'lint_javascript': ()}},
 {'do': {'check_local_config_schema': ()}},
 {'do': {'run_ios': (None,)}, 'when': {'platform_is': 'ios'}}]
2012-11-19 11:38:27,931 [   INFO] Checking JavaScript files...
2012-11-19 11:38:27,931 [  DEBUG] Running: '/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/bin/jsl-64' '-conf' '/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/jsl.conf' '-process' '/home/pilaf/projects/tww/ttw-mobile/src/*.js' '-nologo' '-nofilelisting' '-nosummary'
2012-11-19 11:38:27,995 [   INFO] JavaScript check complete
2012-11-19 11:38:27,995 [   INFO] Verifying your configuration settings...
2012-11-19 11:38:27,995 [   INFO] Configuration settings check complete
2012-11-19 11:38:27,996 [   INFO] Running iOS Simulator
2012-11-19 11:38:27,996 [  ERROR] iOS Simulator is only available on OS X, please change the iOS run settings in your local config to 'device' or a specific device.

To resolve this problem, you can modify the file "local_config.json" to something like:
{
    "ios": {
        "device": "device"
    }
}

Or pass commandline arguments to forge:
forge --ios.device "device"

More information is available at:
http://current-docs.trigger.io/tools/local-config.html#ios

2012-11-19 11:38:27,997 [  DEBUG] Traceback (most recent call last):
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/async.py", line 96, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/main.py", line 437, in run
    build_to_run=build_to_run,
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/customer_goals.py", line 126, in run_app
    build_to_run.run()
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/build.py", line 337, in run
    self._call_with_params(task_method, task_args)
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/build.py", line 296, in _call_with_params
    return method(self, *params)
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/ios_tasks.py", line 603, in run_ios
    runner.run_iphone_simulator(build)
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/ios_tasks.py", line 455, in run_iphone_simulator
    more_info="http://current-docs.trigger.io/tools/local-config.html#ios"
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/lib.py", line 413, in local_config_problem
    raise BASE_EXCEPTION(exc_message)
ForgeError: iOS Simulator is only available on OS X, please change the iOS run settings in your local config to 'device' or a specific device.

To resolve this problem, you can modify the file "local_config.json" to something like:
{
    "ios": {
        "device": "device"
    }
}

Or pass commandline arguments to forge:
forge --ios.device "device"

More information is available at:
http://current-docs.trigger.io/tools/local-config.html#ios


2012-11-19 12:13:54,424 [   INFO] Forge tools running at version 3.3.28
2012-11-19 12:13:54,430 [  DEBUG] Forge build tools version: 3.3.28
2012-11-19 12:13:54,431 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-11-19 12:13:54,441 [  DEBUG] GET https://trigger.io/api/version_check/3/3/28/
2012-11-19 12:13:55,813 [  DEBUG] Checking API response for success or error
2012-11-19 12:13:55,813 [   INFO] Update result: you already have the latest tools
2012-11-19 12:13:55,814 [  DEBUG] GET https://trigger.io/api/auth/loggedin
2012-11-19 12:13:56,480 [  DEBUG] Checking API response for success or error
2012-11-19 12:13:56,480 [  DEBUG] already authenticated via cookie - continuing
2012-11-19 12:13:56,480 [  DEBUG] GET https://trigger.io/api/app/eb276e38325311e29d9a12313d31f141/should_rebuild
2012-11-19 12:13:56,745 [  DEBUG] Checking API response for success or error
2012-11-19 12:13:56,894 [  DEBUG] configuration is identical to last run
2012-11-19 12:13:56,894 [  DEBUG] already authenticated - continuing
2012-11-19 12:13:56,894 [  DEBUG] POST https://trigger.io/api/reload/buildevents/eb276e38325311e29d9a12313d31f141
2012-11-19 12:13:57,260 [  DEBUG] Checking API response for success or error
2012-11-19 12:13:57,260 [  ERROR] Target required for 'forge build', e.g. 'forge build android'
2012-11-19 12:13:57,260 [  DEBUG] Traceback (most recent call last):
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/async.py", line 96, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/main.py", line 358, in development_build
    raise ForgeError(FORGE_BUILD_NEEDS_TARGET)
ForgeError: Target required for 'forge build', e.g. 'forge build android'

2012-11-19 12:27:27,652 [   INFO] Forge tools running at version 3.3.28
2012-11-19 12:27:27,819 [  DEBUG] ignoring non-target directory reload
2012-11-19 12:27:27,819 [  DEBUG] Enabled platforms: ['chrome']
2012-11-19 12:27:27,847 [  DEBUG] Forge build tools version: 3.3.28
2012-11-19 12:27:27,848 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-11-19 12:27:27,848 [  DEBUG] GET https://trigger.io/api/auth/loggedin
2012-11-19 12:27:47,919 [  ERROR] Something went wrong that we didn't expect:
2012-11-19 12:27:47,919 [  ERROR] HTTPSConnectionPool(host='trigger.io', port=443): Max retries exceeded with url: /api/auth/loggedin
2012-11-19 12:27:47,919 [  DEBUG] Traceback (most recent call last):
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/async.py", line 96, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/main.py", line 437, in run
    build_to_run=build_to_run,
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/customer_goals.py", line 125, in run_app
    log_build(build_to_run, "run")
  File "/home/pilaf/projects/tww/ttw-mobile/.template/generate_dynamic/customer_goals.py", line 32, in log_build
    remote._authenticate()
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/remote.py", line 256, in _authenticate
    resp = self._api_get('auth/loggedin')
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/remote.py", line 222, in _api_get
    resp = self.__get_or_post(absolute_url, *args, **kw)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge/remote.py", line 190, in __get_or_post
    resp = getattr(self.session, method.lower())(url, *args, **kw)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge-dependencies/requests/sessions.py", line 225, in get
    return self.request('get', url, **kwargs)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge-dependencies/requests/sessions.py", line 208, in request
    r.send(prefetch=prefetch)
  File "/home/pilaf/projects/tww/vendor/TriggerToolkit/build-tools/forge-dependencies/requests/models.py", line 580, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='trigger.io', port=443): Max retries exceeded with url: /api/auth/loggedin

2012-11-19 12:27:47,920 [  ERROR] See /home/pilaf/projects/tww/ttw-mobile/forge-error.log for more details
2012-11-19 12:27:47,920 [  ERROR] Please contact support@trigger.io
